version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    platform: linux/x86_64
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - ./volumes/mysql/:/var/lib/mysql
  mongodb:
    image: mongo:4.4.3
    platform: linux/x86_64
    env_file: ./.env
    ports:
      - $MONGO_HOST_PORT:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE=admin
    volumes:
      - ./volumes/mongo/data/db/:/data/db/
      - ./volumes/mongo/log/:/var/log/mongodb/
    command: ["--bind_ip", "0.0.0.0"]
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
    volumes: 
      - ./volumes/mosquitto:/mosquitto/config
  fetcher:
    depends_on:
      - mongodb
      - mosquitto
    build: ./fetcher
    env_file: ./.env
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.data.mongodb.authentication-database" : "admin",
        "spring.data.mongodb.auto-index-creation" : "$MONGO_AUTO_INDEX_CREATION",
        "spring.data.mongodb.host" : "mongodb:27017",
        "spring.data.mongodb.port" : "27017",
        "spring.data.mongodb.username" : "$MONGO_ROOT_USERNAME",
        "spring.data.mongodb.password" : "$MONGO_ROOT_PASSWORD",
        "spring.data.mongodb.database" : "$MONGO_DB"
      }'
    volumes:
      - ./volumes/fetcher/:/root/.m2
    stdin_open: true
    tty: true
  app:
    depends_on:
      - mysqldb
      - mongodb
    build: ./student_app
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.data.mongodb.authentication-database" : "admin",
        "spring.data.mongodb.auto-index-creation" : "$MONGO_AUTO_INDEX_CREATION",
        "spring.data.mongodb.host" : "mongodb:27017",
        "spring.data.mongodb.port" : "27017",
        "spring.data.mongodb.username" : "$MONGO_ROOT_USERNAME",
        "spring.data.mongodb.password" : "$MONGO_ROOT_PASSWORD",
        "spring.data.mongodb.database" : "$MONGO_DB"
      }'
    volumes:
      - ./volumes/student/:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
