version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    platform: linux/x86_64
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  mongodb:
    image: "mongo:4.4.3"
    platform: linux/x86_64
    ports:
      - 27017:27017
    volumes:
      - db:/var/lib/mongo
    ports:
      - $MONGO_HOST_PORT:27017
    environment:
      - MONGO_ROOT_USERNAME=$MONGO_ROOT_USERNAME
      - MONGO_ROOT_PASSWORD=$MONGO_ROOT_PASSWORD
      - MONGO_DATABASE=$MONGO_DB
    volumes:
      - $MONGO_DATA_HOST_PATH:/data/db/
      - $MONGO_LOG_HOST_PATH:/var/log/mongodb/
    command: ["--bind_ip", "0.0.0.0"]
  broker:
    depends_on:
      - mongodb
    build: ./broker
    env_file: ./.env
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.data.mongodb.authentication-database" : "$MONGO_DB",
        "spring.data.mongodb.auto-index-creation" : "$MONGO_AUTO_INDEX_CREATION",
        "spring.data.mongodb.host" : "mongodb:27017",
        "spring.data.mongodb.port" : "27017",
        "spring.data.mongodb.username" : "$MONGO_ROOT_USERNAME",
        "spring.data.mongodb.password" : "$MONGO_ROOT_PASSWORD",
        "spring.data.mongodb.database" : "$MONGO_DB"
      }'
    volumes:
      - .m1:/root/.m1
    stdin_open: true
    tty: true
  app:
    depends_on:
      - mysqldb
      - mongodb
    build: ./student-app
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.data.mongodb.authentication-database" : "$MONGO_DB",
        "spring.data.mongodb.auto-index-creation" : "$MONGO_AUTO_INDEX_CREATION",
        "spring.data.mongodb.host" : "mongodb:27017",
        "spring.data.mongodb.port" : "27017",
        "spring.data.mongodb.username" : "$MONGO_ROOT_USERNAME",
        "spring.data.mongodb.password" : "$MONGO_ROOT_PASSWORD",
        "spring.data.mongodb.database" : "$MONGO_DB"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
